/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface RrManifesto {
      'manifestUrl': string;
    }
  }

  interface HTMLRrManifestoElement extends StencilComponents.RrManifesto, HTMLStencilElement {}

  var HTMLRrManifestoElement: {
    prototype: HTMLRrManifestoElement;
    new (): HTMLRrManifestoElement;
  };
  interface HTMLElementTagNameMap {
    'rr-manifesto': HTMLRrManifestoElement;
  }
  interface ElementTagNameMap {
    'rr-manifesto': HTMLRrManifestoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'rr-manifesto': JSXElements.RrManifestoAttributes;
    }
  }
  namespace JSXElements {
    export interface RrManifestoAttributes extends HTMLAttributes {
      'manifestUrl'?: string;
      'onLoadedManifest'?: (event: CustomEvent) => void;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;