/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface RerumManifesto {
      'manifestUrl': string;
    }
  }

  interface HTMLRerumManifestoElement extends StencilComponents.RerumManifesto, HTMLStencilElement {}

  var HTMLRerumManifestoElement: {
    prototype: HTMLRerumManifestoElement;
    new (): HTMLRerumManifestoElement;
  };
  interface HTMLElementTagNameMap {
    'rerum-manifesto': HTMLRerumManifestoElement;
  }
  interface ElementTagNameMap {
    'rerum-manifesto': HTMLRerumManifestoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'rerum-manifesto': JSXElements.RerumManifestoAttributes;
    }
  }
  namespace JSXElements {
    export interface RerumManifestoAttributes extends HTMLAttributes {
      'manifestUrl'?: string;
      'onLoadedManifest'?: (event: CustomEvent) => void;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;